version: '3.8'

services:
  website:
    image: nginx:alpine
    container_name: website
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=kisters.me
      - LETSENCRYPT_HOST=kisters.me
    networks:
      - web

networks:
  web:
    external: true