services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    image: website-static:latest
    container_name: website
    restart: always
    environment:
      - VIRTUAL_HOST=kisters.me
      - LETSENCRYPT_HOST=kisters.me
    networks:
      - web

networks:
  web:
    external: true
